# This is a workflow to build a release when merging to master
name: build-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      # create release
      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}


  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup right Python Version
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      # install python requirements
      - name: install requirements
        run: pip install -r requirements.txt

      # bild the exe
      - name: build
        run: make exe

      - name: Create tarball
        run: |
          cd dist/
          tar czvf ${{ matrix.os }}.tar.gz *

      # upload linux artifact
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/${{ matrix.os }}.tar.gz
          asset_name: ffw-geraetewart-linux
          asset_content_type: application/gzip
