# This is a workflow to build a release when merging to master
name: build-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup right Python Version
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      # install python requirements
      - name: install requirements
        run: pip install -r requirements.txt

      # bild the exe
      - name: build
        run: make exe

      # create release
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create tarball
        uses: master-atul/tar-action@v1.0.2
        run: |
          cd dist/
          tar -czvf ffw-geraetewart-linux.tar.gz *

      # upload linux artifact
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ffw-geraetewart-linux.tar.gz
          asset_name: ffw-geraetewart-linux
          asset_content_type: application/gzip
